[book]
authors = ["xi xiao"]
language = "en"
multilingual = false
src = "src"
title = "Rust & Beyond: A Practical Exploration"

[output.html]
git-repository-url = "https://github.com/xixiaofinland/rust_beyond"
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]

[output.html.playground]
editable = false
